OnlineStore/OnlineStore/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineStore.Models
{
    public class ProductViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Currency { get; set; }
        public int Price { get; set; }
        public virtual CategoryViewModel Category { get; set; }
        public virtual ManufacturerViewModel Manufacturer { get; set; }
    }
}

OnlineStore/OnlineStore/Models/ProductsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineStore.Models
{
    public class ProductsViewModel
    {
        public string SearchQuery { get; set; }
        public IEnumerable<ProductViewModel> Products { get; set; }
    }
}

OnlineStore/OnlineStore/Controllers/ProductsController.cs
using Store.Dal.CodeFirst.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using Store.Dal.CodeFirst.Contracts;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Mappers;
using OnlineStore.Models;

namespace OnlineStore.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository _productRepository;

        public ProductsController()
        {
            _productRepository = new ProductRepository();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductViewModel model)
        {
            _productRepository.Create(model.ToDto());

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Index()
        {
            var products = _productRepository.GetProducts().ToViewModel() ?? new List<ProductViewModel>();
            ViewBag.Products = products;
            return View();
        }
        [HttpGet]
        public ActionResult Details(Guid id)
        {
            var product = _productRepository.GetProduct(id)?.ToViewModel();

            return View(product);
        }
    }
}

OnlineStore/OnlineStore/Views/Products/Create.cshtml
@model OnlineStore.Models.ProductViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Product</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer.Logo, "", new { @class = "text-danger" })
            </div>
        </div><div class="form-group">
            @Html.Label("Manufacturer Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Manufacturer Logo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Manufacturer.Logo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Manufacturer.Logo, "", new { @class = "text-danger" })
                </div>
            </div><div class="form-group">
                @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Category.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Category.Name, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Currency, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

}

OnlineStore/OnlineStore/Views/Products/Details.cshtml
@model OnlineStore.Models.ProductViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.Logo)" height="300" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Manufacturer.Name)
        </dd>
        <dd>
            <img src="@Html.DisplayFor(model => model.Manufacturer.Logo)" width="75" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
            @Html.DisplayFor(model => model.Currency)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineStore/OnlineStore/Views/Products/Index.cshtml
@model OnlineStore.Models.ProductsViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*@using (Html.BeginForm("Index", "Products", new { searchQuery = Model.SearchQuery }, FormMethod.Get))
{
    <div>
        @Html.LabelFor(x => x.SearchQuery)
        @Html.TextBoxFor(x => x.SearchQuery, htmlAttributes: new { placeholder = "Search..." })

        <input type="submit" value="Search" />
    </div>
}*@
@Html.ActionLink("Add Product", "Create")
<table class="table">
    <tr>
        <th>Product</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
    </tr>
    @foreach (var item in ViewBag.Products)
    {
        <tr>
            <td>
                <img src="@item.Logo" width="100" />
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @item.Price @item.Currency
            </td>
            <td>
                @Html.ActionLink("Buy", "#", new { id = item.Id }) |
                @Html.ActionLink("To Cart", "#", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>